spring:
  datasource:
    username: ${MYSQLUSER}
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    password: ${MYSQLPASSWORD}
  thymeleaf:
    enable: 'false'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: ${PORT:8081}
