name: Deploy automático para VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend
      uses: actions/checkout@v3
      with:
        repository: JuniorMoraees/SecurityChildren
        path: backend

    - name: Checkout frontend
      uses: actions/checkout@v3
      with:
        repository: JuniorMoraees/SecurityChildrenSite
        path: frontend

    - name: Enviar backend e frontend para VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_SECRET }}
        source: |
          ./backend
          ./frontend
        target: /root/app

    - name: Rodar Docker Compose na VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_SECRET }}
        script: |
          cd /root/app
          docker compose down
          docker compose up -d --build
